// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlwcidhqptqikklukado.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsd2NpZGhxcHRxaWtrbHVrYWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODk3NDMsImV4cCI6MjA3NDI2NTc0M30.CykOHWPlLMizUJGg7sfj_ulGLysP3rtMVpPVufqZiqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});